//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstApproach2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Cid { get; set; }
        public string Cname { get; set; }
        public string Clocation { get; set; }
        public int Bid { get; set; }
    
        public virtual Bike Bike { get; set; }
    }
}
