//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelfirstschooltask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Stid { get; set; }
        public string Stname { get; set; }
        public string Stgender { get; set; }
        public int Eid { get; set; }
        public int SchoolSid { get; set; }
    
        public virtual School School { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Result Result { get; set; }
    }
}
